# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/meta_notebook',
                'doc_host': 'https://radekosmulski.github.io',
                'git_url': 'https://github.com/radekosmulski/meta_notebook',
                'lib_path': 'meta_notebook'},
  'syms': {'meta_notebook.core': {'meta_notebook.core.foo': ('core.html#foo', 'meta_notebook/core.py')}}}
